main: !MainConfig
  tmp: "./tmp"
  cecil: "/usr/lib/mono-cecil/Mono.Cecil.dll"
converter:
  Donut: !converter.DonutConfig
    path: "/opt/donut"
compiler:
  LLVMPass: !compiler.LLVMPassConfig
    clang: "/usr/local/bin/x86_64-w64-mingw32-clang"
    clangpp: "/usr/local/bin/x86_64-w64-mingw32-clang++"
    windres: "/usr/bin/llvm-windres-16"
    plugin: "/opt/libSsageObfuscator.so"
